apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tic-tac-toe-tls
  namespace: tic-tac-toe
spec:
  acme:
    config:
    - domains:
      - tictactoe.keithbartholomew.com
      http01:
        ingressClass: nginx
  commonName: tictactoe.keithbartholomew.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: tic-tac-toe-tls
