#!/bin/bash
set -euo pipefail

container_exists=$(docker ps -a -q -f name=ttt_redis_data)

if [[ -z ${container_exists} ]]; then
  docker run \
  --name ttt_redis_data \
  --volume /data \
  redis \
  /bin/true
fi
