#!/bin/bash
set -euo pipefail

container_exists=$(docker ps -a -q -f name=ttt_htpasswd_data)

if [[ -z ${container_exists} ]]; then
  docker run \
  --name ttt_htpasswd_data \
  --env affinity:container==ttt_nginx_config_data \
  --volume /etc/nginx/htpasswd \
  nginx \
  /bin/true
fi

docker run --rm \
--volumes-from ttt_htpasswd_data \
httpd \
htpasswd -bc /etc/nginx/htpasswd/rethinkdb rethinkdb ${NGINX_RETHINKDB_PASS}
