#!/bin/bash
set -euo pipefail

docker run \
--name nginx-htpasswd-data \
--volume /etc/nginx/htpasswd \
nginx \
/bin/true

docker run --rm \
--volumes-from nginx-htpasswd-data \
httpd \
htpasswd -bc /etc/nginx/htpasswd/rethinkdb rethinkdb ${NGINX_RETHINKDB_PASS}
