#!/bin/bash
set -euo pipefail

scale=${1:-1}
color=${2:-}

if [[ -z ${color} ]]; then
  echo "Usage: $(basename ${0}) <scale=1> <color>"
  exit 1
fi

docker ps -q -f name=ttt_app_${color} -f label=color=${color} | xargs docker rm -f

for i in $(seq 1 ${scale}); do
  docker run \
  -d \
  --label color=${color} \
  --name=ttt_app_${color}_${i} \
  -e affinity:image==ttt_app \
  -e REDIS_HOST=ttt_redis \
  -e RETHINKDB_HOST=ttt_db \
  --net tictactoe \
  --restart=always \
  ttt_app
done;
