#!/bin/bash
set -euo pipefail

if [[ $(docker inspect -f {{.ID}} ttt_redis 2> /dev/null) != "" ]]; then
  docker rm -f ttt_redis
fi

docker run \
--detach \
--name ttt_redis \
--env affinity:container==ttt_redis_data \
--net tictactoe \
--volumes-from ttt_redis_data \
redis
