#!/bin/bash
set -euo pipefail

if [[ $(docker inspect -f {{.ID}} ttt_nginx_proxy 2> /dev/null) != "" ]]; then
  docker rm -f ttt_nginx_proxy
fi

docker run \
-d \
--name ttt_nginx_proxy \
--link ttt_db:db \
-p 443:443 \
-p 80:80 \
--restart always \
--volumes-from ttt_frontend_data \
--volumes-from ttt_htpasswd_data \
--volumes-from ttt_letsencrypt_data \
nginx_proxy
