#!/bin/bash
set -euo pipefail

if [[ $(docker inspect -f {{.ID}} ttt_db 2> /dev/null) != "" ]]; then
  docker rm -f ttt_db
fi

docker run \
--detach \
--name ttt_db \
--env affinity:container==ttt_db_data \
--net tictactoe \
--restart always \
--volumes-from ttt_db_data \
rethinkdb
