#!/bin/bash
set -euo pipefail

root=$(cd $(dirname ${0})/..; pwd)

NODE_ENV=production ${root}/frontend/script/compile-assets

cd ${root}/frontend/src

docker cp ./ ttt_frontend_data:/usr/share/nginx/html/
